### PR TITLE
Homework 1 - Pull request to remote repository

### PR DESCRIPTION
**Pull request by BrunoMartinsons**
- Learned how to fork and clone a repository into my local directory. Then made changes, committed them and pushed into my remote forked repository. 

- Now I am creating a pull request into the remote repository of the project. This means that my pull request will be reviewed and can then be merged into the source project.

### CODE REVIEW

**Comment by Almantask** [comment]
Yes, first step is good. But normally you add code with the pull request itself, therefore it's homework 1&2. But good start! :)

**Comment by Almantask** [comment]
Not a bad start. For now, don't bother yourself too much with validation- that will be done in the next homework along with if statements. In fact even making your own functions is not absolutely needed. 

However, there is one thing that I would like to pick on- naming. Question is not a good name for a function, because it's a noun. What does it mean? It should be AskQuestion at least. In any case, it's more like PromptForBmi or similar.

**Comment by Almantask** [comment]
I presume this is not finished based on your own comments in code, so I will not flag it as anything just yet.

**Comment by BrunoMartinsons** [comment]
> 
> 
> I presume this is not finished based on your own comments in code, so I will not flag it as anything just yet.

Hello, thank you for your comments. I have completed this exercise for now (might try to refactor it later on). I do see the mistake that I made by pulling before completing the coding exercise (so every time i committed and pushed to the remote repository it goes into the pull request too). I will know this for next time.

**Comment by Almantask** [comment]
Keep it up ;)

**Pull request closed without merging**
