### PR TITLE
Chap 2 Homework 3 from Aurora

### PR DESCRIPTION
**Pull request by Aurora2500**

### CODE REVIEW

**Comment by Aurora2500** [comment]
I don't see why this would be labeled Chapter 2 Homework 3.  I just saw a mistake in one of the file names.

**Comment by Almantask** [comment]
Ofc you cannot see why, you didn't have the lesson yet and don't understand the main point 😊

**Comment by Aurora2500** [comment]
After having watched the lesson, I still don't see the point in having the file the MacFactory class is in be called MsFactory - Copy.cs :p

**Comment by Aurora2500** [comment]
Anyway gonna use this PR for homework when I have time

**Pull request merged**
